name: 自动登录 serv00 ssh
on:
  workflow_dispatch:
  schedule:
    - cron: '13 21 * * 1'  # 每周一登录一次

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ~/.ssh
      - run: |
          cat > ~/.ssh/id_rsa <<EOF
          ${{ secrets.ID_RSA }}
          EOF
      - run: chmod +rw ~/.ssh/id_rsa
      - run: echo "date +\"%Y-%m-%d %H:%M:%S\" >> autoLoginLog.txt" | ssh ${{ secrets.USER }}@${{ secrets.SERVER }} -p 80 -o StrictHostKeyChecking=no

